### ISSUE TITLE
use global failAction instead of route-specific one

### ISSUE THREAD

**Issue by midnightcodr** [ignivalancy/hano#1]
I see that you set the same failAction for every single route. There's a better way accomplish that. You can set it when you create the hapi server instance

```javascript
const server = Hapi.Server({
    // ...
    routes: {
        validate: {
            failAction: failActionJoi
        }
    }
})
```
For details see https://hapijs.com/api#-routeoptionsvalidatefailaction

**Comment by ignivalancy** [comment]
thanks @midnightcodr ... updation done .
